# Host to use for canonical URL generation (without trailing slash)
host: https://www.payments.service.gov.uk/

# Header-related options
show_govuk_logo: true
service_name: Pay
service_link: https://www.payments.service.gov.uk/
phase: Beta

# Links to show on right-hand-side of header
header_links:
  About: https://www.payments.service.gov.uk/#main
  Get started: https://www.payments.service.gov.uk/getstarted/
  Documentation: /
  Support: https://www.payments.service.gov.uk/support/
  Sign In: https://selfservice.payments.service.gov.uk/login

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id: UA-72121642-9

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 3

# Prevent robots from indexing (e.g. whilst in development)

google_site_verification: "IJ5HOXpZrISM6la-YO_iX0rBUC5YFftpexygcKLsNs4"

multipage_nav: true
collapsible_nav: true

enable_search: true

